
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vscodium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vscodium
  template:
    metadata:
      labels:
        app: vscodium
    spec:
      containers:
        - name: vscodium
          image: lscr.io/linuxserver/vscodium:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Etc/CET
          ports:
            - containerPort: 80
            - containerPort: 81
          volumeMounts:
            - name: vscodium-config
              mountPath: /config
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
            seccompProfile:
              type: Unconfined
          resources:
            limits:
              shm: 1Gi
      volumes:
        - name: vscodium-config
          hostPath:
            path: /vscodium
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: vscodium
spec:
  selector:
    app: vscodium
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 81
      targetPort: 81
  type: ClusterIP
